[package]
name = "youtube_to_m3u8"
version = "0.1.0"
authors = ["tktcorporation <tktcorporation.go@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curl = "0.4.34"
regex = "1"