name: Test

on:
  push:

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  test:
    name: Rust ${{ matrix.os }} ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        rust:
          - stable
        os: [ubuntu-latest]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: ${{ matrix.rust }}
          override: true

      - name: fmt
        run: cargo fmt --all -- --check

      - name: clippy
        run: cargo clippy --all -- -D warnings

      - name: test
        run: RUST_BACKTRACE=1 cargo test --verbose --all -- --nocapture